apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: memcached-exporter-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    name: memcached-exporter-service-monitor
    exporter: memcached-exporter
spec:
  selector:
    matchLabels:
      prometheus-exporter/target: memcached
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      interval: 5s
      # In order to keep timeseries, need to drop unwanted labels
      relabelings:
        - regex: (container|endpoint|namespace|pod|service)
          action: labeldrop
      metricRelabelings:
        - regex: (instance|job)
          action: labeldrop
  targetLabels:
    - prometheus-exporter/host-and-port
